# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cute-T Stickers' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cute-T Stickers

pod 'SDWebImage', '~> 5.0'
pod 'AFNetworking', '~> 1.3.3'
pod 'Toast', '~> 4.0.0'

end

target 'Cute-T Stickers iMessage Extension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cute-T Stickers iMessage Extension

pod 'SDWebImage', '~> 5.0'

end
